"""FastAPI MCP Discovery and Installation Server.

This server provides:
1. Web interface for discovering MCP servers
2. HITL approval via web UI
3. Server installation and testing
4. Real-time status updates via WebSocket
"""

import subprocess
import sys
import tempfile
from contextlib import asynccontextmanager
from datetime import datetime
from pathlib import Path

# FastAPI imports
from fastapi import FastAPI, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

# Import our MCP tools
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))

from haive.core.engine.aug_llm import AugLLMConfig
from langchain_mcp_adapters.client import MultiServerMCPClient

from haive.mcp.working_enhanced_retriever import WorkingEnhancedRetriever


# Models
class SearchRequest(BaseModel):
    query: str
    max_results: int = 5


class InstallRequest(BaseModel):
    server_name: str
    auto_approve: bool = False


class TestRequest(BaseModel):
    server_name: str


class ApprovalResponse(BaseModel):
    request_id: str
    approved: bool
    notes: str | None = None


class ServerInfo(BaseModel):
    name: str
    category: str
    stars: int
    language: str
    description: str
    has_install: bool
    repository_url: str


# Global state
class MCPServerManager:
    def __init__(self):
        self.retriever = None
        self.installed_servers: dict[str, dict] = {}
        self.pending_approvals: dict[str, dict] = {}
        self.websocket_clients: list[WebSocket] = []
        self.engine = None
        self.llm = None

    async def initialize(self):
        """Initialize the retriever and LLM."""
        print("🔧 Initializing MCP Server Manager...")

        # Setup retriever
        self.retriever = WorkingEnhancedRetriever()
        self.retriever.setup()

        # Setup LLM
        self.engine = AugLLMConfig(
            name="mcp_discovery", model="gpt-3.5-turbo", temperature=0.3
        )
        self.llm = self.engine.instantiate()

        print("✅ MCP Server Manager ready!")

    async def broadcast_message(self, message: dict):
        """Broadcast message to all connected WebSocket clients."""
        disconnected = []
        for ws in self.websocket_clients:
            try:
                await ws.send_json(message)
            except:
                disconnected.append(ws)

        # Clean up disconnected clients
        for ws in disconnected:
            self.websocket_clients.remove(ws)

    async def search_servers(
        self, query: str, max_results: int = 5
    ) -> list[ServerInfo]:
        """Search for MCP servers using enhanced retriever."""
        docs = await self.retriever.enhanced_query(self.llm, query, max_results)

        servers = []
        for doc in docs:
            server = ServerInfo(
                name=doc.metadata.get("server_name", "Unknown"),
                category=doc.metadata.get("category", "general"),
                stars=doc.metadata.get("stars", 0),
                language=doc.metadata.get("language", "unknown"),
                description=doc.page_content[:200] + "...",
                has_install=doc.metadata.get("has_install", False),
                repository_url=doc.metadata.get("repository_url", ""),
            )
            servers.append(server)

        return servers

    async def request_install_approval(self, server_name: str) -> str:
        """Request approval for server installation."""
        request_id = f"install_{server_name}_{datetime.now().timestamp()}"

        self.pending_approvals[request_id] = {
            "type": "install",
            "server_name": server_name,
            "timestamp": datetime.now().isoformat(),
            "status": "pending",
        }

        # Broadcast approval request
        await self.broadcast_message(
            {
                "type": "approval_request",
                "request_id": request_id,
                "server_name": server_name,
                "action": "install",
                "timestamp": datetime.now().isoformat(),
            }
        )

        return request_id

    async def install_server(self, server_name: str) -> dict:
        """Install an MCP server."""
        # Generate FastMCP server code
        server_code = f'''"""
FastMCP Server: {server_name}
Auto-generated by Haive MCP Manager
"""

from fastmcp import FastMCP
from typing import Dict, List

mcp = FastMCP("{server_name}")

@mcp.tool()
async def hello(name: str = "World") -> str:
    """Say hello."""
    return f"Hello {{name}}! This is {server_name}."

@mcp.tool()
async def get_info() -> Dict[str, Any]:
    """Get server information."""
    return {{
        "server": "{server_name}",
        "status": "running",
        "version": "1.0.0"
    }}

@mcp.resource("server://info")
async def server_info() -> str:
    """Server information resource."""
    return f"{server_name} MCP Server - Running"

@mcp.prompt()
async def help_prompt() -> List[Dict[str, str]]:
    """Generate help prompt."""
    return [{{
        "role": "user",
        "content": f"How can I use {server_name} effectively?"
    }}]

if __name__ == "__main__":
    mcp.run(transport="stdio")
'''

        # Write to temp file
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            f.write(server_code)
            server_path = f.name

        # Store installation info
        self.installed_servers[server_name] = {
            "path": server_path,
            "installed_at": datetime.now().isoformat(),
            "status": "installed",
        }

        # Broadcast installation success
        await self.broadcast_message(
            {
                "type": "install_complete",
                "server_name": server_name,
                "path": server_path,
            }
        )

        return {"server_name": server_name, "path": server_path, "status": "installed"}

    async def test_server(self, server_name: str) -> dict:
        """Test an installed MCP server."""
        if server_name not in self.installed_servers:
            raise HTTPException(
                status_code=404, detail=f"Server {server_name} not installed"
            )

        server_info = self.installed_servers[server_name]
        server_path = server_info["path"]

        # Create MCP client
        client_config = {
            server_name: {
                "command": sys.executable,
                "args": [server_path],
                "transport": "stdio",
            }
        }

        client = MultiServerMCPClient(client_config)
        results = {
            "server_name": server_name,
            "tools": [],
            "resources": [],
            "prompts": [],
            "test_results": {},
        }

        try:
            async with client.session(server_name) as session:
                # List tools
                tools_result = await session.list_tools()
                if hasattr(tools_result, "tools"):
                    results["tools"] = [
                        {"name": t.name, "description": t.description}
                        for t in tools_result.tools
                    ]

                    # Test first tool
                    if tools_result.tools:
                        tool = tools_result.tools[0]
                        test_result = await session.call_tool(
                            tool.name,
                            arguments=(
                                {"name": "FastAPI"} if tool.name == "hello" else {}
                            ),
                        )
                        results["test_results"]["tool"] = str(test_result)

                # List resources
                resources_result = await session.list_resources()
                if hasattr(resources_result, "resources"):
                    results["resources"] = [
                        {"uri": r.uri, "name": r.name}
                        for r in resources_result.resources
                    ]

                # List prompts
                prompts_result = await session.list_prompts()
                if hasattr(prompts_result, "prompts"):
                    results["prompts"] = [
                        {"name": p.name, "description": p.description}
                        for p in prompts_result.prompts
                    ]

        except Exception as e:
            results["errof"] = str(e)

        # Broadcast test results
        await self.broadcast_message(
            {"type": "test_complete", "server_name": server_name, "results": results}
        )

        return results


# Create manager instance
manager = MCPServerManager()


# Lifespan context manager
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    await manager.initialize()
    yield
    # Shutdown
    print("Shutting down...")


# Create FastAPI app
app = FastAPI(
    title="MCP Discovery & Installation Server",
    description="Discover, install, and test MCP servers with HITL approval",
    version="1.0.0",
    lifespan=lifespan,
)

# Add CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Routes
@app.get("/", response_class=HTMLResponse)
async def root():
    """Serve the web UI."""
    return """
<!DOCTYPE html>
<html>
<head>
    <title>MCP Server Manager</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        .search-box {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
        }
        input {
            flex: 1;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
        }
        button {
            padding: 10px 20px;
            background: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button:hover {
            background: #0056b3;
        }
        button:disabled {
            background: #ccc;
            cursor: not-allowed;
        }
        .server-card {
            border: 1px solid #ddd;
            padding: 15px;
            margin: 10px 0;
            border-radius: 4px;
            background: #f9f9f9;
        }
        .server-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .server-info {
            font-size: 14px;
            color: #666;
            margin: 5px 0;
        }
        .approval-request {
            background: #fff3cd;
            border: 1px solid #ffeeba;
            padding: 15px;
            margin: 10px 0;
            border-radius: 4px;
        }
        .test-results {
            background: #d4edda;
            border: 1px solid #c3e6cb;
            padding: 15px;
            margin: 10px 0;
            border-radius: 4px;
        }
        .error {
            background: #f8d7da;
            border: 1px solid #f5c6cb;
            padding: 15px;
            margin: 10px 0;
            border-radius: 4px;
        }
        .status {
            padding: 10px;
            margin: 10px 0;
            border-radius: 4px;
            font-family: monospace;
            font-size: 12px;
        }
        pre {
            background: #f4f4f4;
            padding: 10px;
            border-radius: 4px;
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <h1>🚀 MCP Server Discovery & Installation</h1>
    
    <div class="container">
        <h2>Search MCP Servers</h2>
        <div class="search-box">
            <input type="text" id="searchQuery" placeholder="e.g., Python database servers with high stars" />
            <button onclick="searchServers()">Search</button>
        </div>
        <div id="searchResults"></div>
    </div>
    
    <div class="container">
        <h2>Installed Servers</h2>
        <div id="installedServers"></div>
    </div>
    
    <div class="container">
        <h2>Status & Logs</h2>
        <div id="statusLog" class="status"></div>
    </div>
    
    <script>
        let ws = null;
        let installedServers = {};
        
        // Initialize WebSocket
        function initWebSocket() {
            ws = new WebSocket('ws://localhost:6969/ws');
            
            ws.onopen = () => {
                addStatus('✅ Connected to server');
            };
            
            ws.onmessage = (event) => {
                const data = JSON.parse(event.data);
                handleWebSocketMessage(data);
            };
            
            ws.onclose = () => {
                addStatus('❌ Disconnected from server');
                setTimeout(initWebSocket, 3000);
            };
        }
        
        // Handle WebSocket messages
        function handleWebSocketMessage(data) {
            switch(data.type) {
                case 'approval_request':
                    showApprovalRequest(data);
                    break;
                case 'install_complete':
                    addStatus(`✅ Installed: ${data.server_name}`);
                    loadInstalledServers();
                    break;
                case 'test_complete':
                    showTestResults(data);
                    break;
                default:
                    addStatus(`📨 ${data.type}: ${JSON.stringify(data)}`);
            }
        }
        
        // Show approval request
        function showApprovalRequest(data) {
            const html = `
                <div class="approval-request" id="approval_${data.request_id}">
                    <h3>🔔 Approval Required</h3>
                    <p>Install MCP Server: <strong>${data.server_name}</strong></p>
                    <button onclick="approveInstall('${data.request_id}', true)">Approve</button>
                    <button onclick="approveInstall('${data.request_id}', false)">Reject</button>
                </div>
            `;
            document.getElementById('statusLog').insertAdjacentHTML('afterbegin', html);
        }
        
        // Approve installation
        async function approveInstall(requestId, approved) {
            const response = await fetch('/approve', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({
                    request_id: requestId,
                    approved: approved
                })
            });
            
            document.getElementById(`approval_${requestId}`).remove();
            addStatus(approved ? '✅ Installation approved' : '❌ Installation rejected');
        }
        
        // Search servers
        async function searchServers() {
            const query = document.getElementById('searchQuery').value;
            if (!query) return;
            
            addStatus(`🔍 Searching: ${query}`);
            
            const response = await fetch('/search', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({query: query, max_results: 5})
            });
            
            const servers = await response.json();
            displaySearchResults(servers);
        }
        
        // Display search results
        function displaySearchResults(servers) {
            const html = servers.map(server => `
                <div class="server-card">
                    <div class="server-headef">
                        <h3>${server.name}</h3>
                        <button onclick="installServer('${server.name}')">Install</button>
                    </div>
                    <div class="server-info">
                        <strong>Category:</strong> ${server.category} | 
                        <strong>Language:</strong> ${server.language} | 
                        <strong>Stars:</strong> ${server.stars}
                    </div>
                    <p>${server.description}</p>
                    <a href="${server.repository_url}" target="_blank">View Repository</a>
                </div>
            `).join('');
            
            document.getElementById('searchResults').innerHTML = html;
        }
        
        // Install server
        async function installServer(serverName) {
            addStatus(`📦 Requesting installation: ${serverName}`);
            
            const response = await fetch('/install', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({
                    server_name: serverName,
                    auto_approve: false
                })
            });
            
            const result = await response.json();
            if (result.error) {
                addStatus(`❌ Error: ${result.error}`);
            }
        }
        
        // Test server
        async function testServer(serverName) {
            addStatus(`🧪 Testing: ${serverName}`);
            
            const response = await fetch('/test', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({server_name: serverName})
            });
            
            const results = await response.json();
            showTestResults({server_name: serverName, results: results});
        }
        
        // Show test results
        function showTestResults(data) {
            const results = data.results;
            const html = `
                <div class="test-results">
                    <h3>🧪 Test Results: ${data.server_name}</h3>
                    <p><strong>Tools:</strong> ${results.tools.map(t => t.name).join(', ')}</p>
                    <p><strong>Resources:</strong> ${results.resources.map(r => r.uri).join(', ')}</p>
                    <p><strong>Prompts:</strong> ${results.prompts.map(p => p.name).join(', ')}</p>
                    ${results.test_results.tool ? `<p><strong>Tool Test:</strong> ${results.test_results.tool}</p>` : ''}
                    ${results.error ? `<p class="errof">Error: ${results.error}</p>` : ''}
                </div>
            `;
            document.getElementById('statusLog').insertAdjacentHTML('afterbegin', html);
        }
        
        // Load installed servers
        async function loadInstalledServers() {
            const response = await fetch('/installed');
            installedServers = await response.json();
            
            const html = Object.entries(installedServers).map(([name, info]) => `
                <div class="server-card">
                    <div class="server-header">
                        <h4>${name}</h4>
                        <button onclick="testServer('${name}')">Test</button>
                    </div>
                    <div class="server-info">
                        Installed: ${new Date(info.installed_at).toLocaleString()}
                    </div>
                </div>
            `).join('') || '<p>No servers installed yet</p>';
            
            document.getElementById('installedServers').innerHTML = html;
        }
        
        // Add status message
        function addStatus(message) {
            const timestamp = new Date().toLocaleTimeString();
            const html = `<div>[${timestamp}] ${message}</div>`;
            const statusLog = document.getElementById('statusLog');
            statusLog.insertAdjacentHTML('afterbegin', html);
            
            // Keep only last 20 messages
            while (statusLog.children.length > 20) {
                statusLog.removeChild(statusLog.lastChild);
            }
        }
        
        // Initialize
        initWebSocket();
        loadInstalledServers();
    </script>
</body>
</html>
"""


@app.post("/search")
async def search_servers(request: SearchRequest):
    """Search for MCP servers."""
    servers = await manager.search_servers(request.query, request.max_results)
    return servers


@app.post("/install")
async def install_server(request: InstallRequest):
    """Install an MCP server."""
    if request.auto_approve:
        # Direct installation
        result = await manager.install_server(request.server_name)
        return result
    # Request approval
    request_id = await manager.request_install_approval(request.server_name)
    return {"status": "approval_pending", "request_id": request_id}


@app.post("/approve")
async def approve_installation(response: ApprovalResponse):
    """Approve or reject an installation."""
    if response.request_id not in manager.pending_approvals:
        raise HTTPException(status_code=404, detail="Approval request not found")

    approval = manager.pending_approvals[response.request_id]

    if response.approved:
        # Install the server
        server_name = approval["server_name"]
        result = await manager.install_server(server_name)
        del manager.pending_approvals[response.request_id]
        return result
    # Reject
    del manager.pending_approvals[response.request_id]
    return {"status": "rejected"}


@app.post("/test")
async def test_server(request: TestRequest):
    """Test an installed MCP server."""
    return await manager.test_server(request.server_name)


@app.get("/installed")
async def get_installed_servers():
    """Get list of installed servers."""
    return manager.installed_servers


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """WebSocket endpoint for real-time updates."""
    await websocket.accept()
    manager.websocket_clients.append(websocket)

    try:
        while True:
            # Keep connection alive
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.websocket_clients.remove(websocket)


if __name__ == "__main__":
    import uvicorn

    # Ensure FastMCP is installed
    try:
        import fastmcp
    except ImportError:
        print("Installing FastMCP...")
        subprocess.run([sys.executable, "-m", "pip", "install", "fastmcp"], check=True)

    print("🚀 Starting MCP Discovery & Installation Server")
    print("📍 Open http://localhost:6969 in your browser")

    uvicorn.run(app, host="0.0.0.0", port=6969)
