"""
Sphinx configuration for haive-mcp.

This configuration uses PyDevelop-Docs shared configuration.
Generated by pydevelop-docs init.
"""

import os
import sys
from datetime import date

# -- Path setup --------------------------------------------------------------
sys.path.insert(0, os.path.abspath("../../src"))

# -- Project information -----------------------------------------------------
project = "haive-mcp"
copyright = f"{date.today().year}, haive-mcp Team"
author = "haive-mcp Team"
release = "0.1.0"

# -- Import shared configuration from pydevelop_docs -------------------------
from pydevelop_docs.config import get_haive_config

# Get the standardized configuration
_config = get_haive_config(
    project, os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

# Apply all configuration settings
for key, value in _config.items():
    if key not in ["project", "copyright", "author", "release"]:
        globals()[key] = value

# -- Project-specific overrides ----------------------------------------------
# Override autoapi_dirs for this specific project structure
autoapi_dirs = ["../../src"]

# Add custom CSS files
html_css_files = html_css_files if "html_css_files" in globals() else []
html_css_files.append("enhanced-index.css")

# -- Viewcode configuration for source viewing ------------------------------
# Use viewcode extension for local source code viewing (works with Furo)
# Removed linkcode_resolve function to avoid conflict with viewcode

# -- Additional setup --------------------------------------------------------


def setup(app):
    """Sphinx setup hook."""
    if os.path.exists("_static/css/custom.css"):
        app.add_css_file("css/custom.css")
    if os.path.exists(
        os.path.join(os.path.dirname(__file__), "_static/enhanced-index.css")
    ):
        app.add_css_file("enhanced-index.css")
    if os.path.exists("_static/js/api-enhancements.js"):
        app.add_js_file("js/api-enhancements.js")
